name: AzoPerks
author: Azorimor
version: 1.0.1
main: io.github.azorimor.azoperks.AzoPerks
website: https://github.com/Azorimor
api-version: 1.13
commands:
  perks:
    description: Opens the perks gui, where you can manage your perks settings.
    usage: perks
  perksinfo:
    description: Shows information about activated perks of a specific player.
    usage: perksinfo <player>
  azoperks:
    description: Shows information about the plugin.
    usage: azoperks
  perk:
    description: Toogles the perk status.
    usage: perk <perk>